#pragma once

// SERVER ---> CLIENT
// SIGN IN 
#define SRV_MSG_SIGN_IN_SUCCESS "1020"
#define SRV_MSG_SIGN_IN_WRONG_DET "1021"
#define SRV_MSG_SIGN_IN_ALREADY_CONNECTED "1022"

// SIGN UP
#define SRV_MSG_SIGN_UP_SUCCESS "1040"
#define SRV_MSG_SIGN_UP_PASS_ILLEGAL "1041"
#define SRV_MSG_SIGN_UP_USER_EXIST "1042"
#define SRV_MSG_SIGN_UP_USERNAME_ILLEGAL "1043"
#define SRV_MSG_SIGN_UP_FAILED "1044"

// ROOM
#define SRV_MSG_JOIN_ROOM_SUCCESS "1100"
#define SRV_MSG_JOIN_ROOM_FULL "1101"
#define SRV_MSG_JOIN_ROOM_NOT_EXIST "1102"
#define SRV_MSG_LEAVE_ROOM_SUCCESS "1120"
#define SRV_MSG_CREATE_ROOM_SUCCESS "1140"
#define SRV_MSG_CREATE_ROOM_FAILED "1141"
#define SRV_MSG_CLOSE_ROOM "116"
#define SRV_MSG_USERS_IN_ROOM "108"

// LOBY
#define SRV_MSG_ROOM_LIST "106"

// Game
#define SRV_MSG_GAME_QUESTION "118"
#define SRV_MSG_GAME_ANSWER_IND "120"
#define SRV_MSG_GAME_FINISH "121"

// REPORTS
#define SRV_MSG_REP_BEST_SCORES 124
#define SRV_MSG_REP_PERSONAL_STATUS 126


// CLIENT ---> SERVER

//CONNECTION
#define CLT_END_CONNECTION 299

// SIGN 
#define CLT_MSG_SIGN_IN 200
#define CLT_MSG_SIGN_OUT 201
#define CLT_MSG_SIGN_UP 203

// LOBY
#define CLT_MSG_GET_ROOMS 205
#define CLT_MSG_GET_USERS_IN_ROOM 207

// ROOM
#define CLT_MSG_CREATE_ROOM 213
#define CLT_MSG_CLOSE_ROOM 215
#define CLT_MSG_LEAVE_ROOM 211
#define CLT_MSG_JOIN_ROOM 209

// GAME
#define CLT_MSG_START_GAME 217
#define CLT_MSG_ANSWER 219
#define CLT_MSG_LEAVE_GAME 222

// REPORTS
#define CLT_MSG_REP_BEST_SCORES 223
#define CLT_MSG_REP_PERSONAL_STATUS 225